version: "3.9"
services:
  problem1-1:
   build: ../problem1-1
   ports:
     - 3004
  problem1-2:
   build: ../problem1-2
   ports:
     - 3005
  problem1-3:
   build: ../problem1-3
   ports:
     - 3006